/**
 * Demo content for `npm run seed`. Prices are realistic Bikaner bakery rates in
 * INR. Product photography points at local Bake Baba'z assets in `public/`,
 * with a few broad-category fallbacks kept for collections not photographed yet.
 */
const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;
const product = (file: string) => `/products/${file}`;
const instagram = (file: string) => `/brand/instagram/${file}`;

export const IMG = {
  ogImage: "/brand/bake-babaz-og.jpg",
  aiHero: "/brand/ai-bakery-hero.png",
  tieredCake: instagram("customised-cakes.jpeg"),
  chocolateCake: product("chocolate-truffle-cake.jpg"),
  chocolateCake2: product("chocolate-mousse-cake.jpg"),
  berryCake: product("blueberry-cake.jpg"),
  birthdayCake: product("strawberry-cake.jpg"),
  decorating: product("strawberry-blueberry-mix-cake.jpg"),
  cookies: product("chocolate-cupcakes.jpg"),
  cookies2: instagram("chocolate-chip-cookies.jpeg"),
  bread: u("photo-1509440159596-0249088772ff"),
  bread2: u("photo-1509365465985-25d11c17e812"),
  dessert: product("chocolate-mousse-pastry.jpg"),
  elegantCake: product("vanilla-cake.jpg"),
  brownies: product("brownie.jpg"),
  cake3: product("blackforest-cake.jpg"),
  cheesecake: product("cheesecake.jpg"),
  cake4: product("butterscotch-cake.jpg"),
  cake5: product("pineapple-cake.jpg"),
  chocolate: product("assorted-homemade-flavored-chocolate-12pc.jpg"),
  cake6: product("strawberry-cake.jpg"),
  cake7: product("strawberry-blueberry-mix-cake.jpg"),
  cake8: product("biscoff-cheesecake-slice.jpg"),
  cake9: instagram("customised-cakes.jpeg"),
  cake10: product("nutella-cheesecake-slice.jpg"),
  cake11: product("pineapple.jpg"),
  cake12: instagram("sewing-machine-themed-cake.jpeg"),
  cake13: instagram("bento-cakes.jpeg"),
  cake14: instagram("flowery-cupcake-basket.jpeg"),
  cake15: product("strawberry-blueberry-mix-pastry.jpg"),
  cake16: product("blueberry-cheesecake-slice.jpg"),
  cake17: product("homemade-flavor-chocolate-bar.jpg"),
  macarons: product("assorted-homemade-flavored-chocolate-6pc.jpg"),
  cake18: product("jalapeno-snacks.jpg"),
  cupcakes: product("chocolate-cupcakes.jpg"),
  assortedChocolate4Pc: product("assorted-homemade-flavored-chocolate-4pc.jpg"),
  assortedChocolate6Pc: product("assorted-homemade-flavored-chocolate-6pc.jpg"),
  assortedChocolate12Pc: product(
    "assorted-homemade-flavored-chocolate-12pc.jpg",
  ),
  biscoffCheesecakeSlice: product("biscoff-cheesecake-slice.jpg"),
  blackforestCake: product("blackforest-cake.jpg"),
  blueberryCake: product("blueberry-cake.jpg"),
  blueberryCheesecakeSlice: product("blueberry-cheesecake-slice.jpg"),
  brownie: product("brownie.jpg"),
  butterscotchCake: product("butterscotch-cake.jpg"),
  cheesecakeWhole: product("cheesecake.jpg"),
  chocolateCupcakes: product("chocolate-cupcakes.jpg"),
  chocolateMousseCake: product("chocolate-mousse-cake.jpg"),
  chocolateMoussePastry: product("chocolate-mousse-pastry.jpg"),
  chocolateTruffleCake: product("chocolate-truffle-cake.jpg"),
  homemadeFlavorChocolateBar: product("homemade-flavor-chocolate-bar.jpg"),
  jalapenoSnacks: product("jalapeno-snacks.jpg"),
  nutellaCheesecakeSlice: product("nutella-cheesecake-slice.jpg"),
  pineappleCake: product("pineapple-cake.jpg"),
  pineapplePastry: product("pineapple-pastry.jpg"),
  pineappleFloralCake: product("pineapple.jpg"),
  strawberryBlueberryMixCake: product("strawberry-blueberry-mix-cake.jpg"),
  strawberryBlueberryMixPastry: product("strawberry-blueberry-mix-pastry.jpg"),
  strawberryCake: product("strawberry-cake.jpg"),
  vanillaCake: product("vanilla-cake.jpg"),
};

export const categories = [
  {
    name: "Custom Cakes",
    slug: "custom-cakes",
    icon: "🎂",
    description:
      "Wedding, birthday and milestone cakes designed around your story.",
    image: IMG.tieredCake,
    featured: true,
    sortOrder: 1,
    prepTimeHours: 24,
  },
  {
    name: "Birthday Cakes",
    slug: "birthday-cakes",
    icon: "🎉",
    description: "Bright, generous cakes made for candles and loud singing.",
    image: IMG.birthdayCake,
    featured: false,
    sortOrder: 2,
    prepTimeHours: 8,
  },
  {
    name: "Anniversary Cakes",
    slug: "anniversary-cakes",
    icon: "💐",
    description: "Elegant cakes for the years worth celebrating properly.",
    image: IMG.berryCake,
    featured: false,
    sortOrder: 3,
    prepTimeHours: 12,
  },
  {
    name: "Wedding Cakes",
    slug: "wedding-cakes",
    icon: "💍",
    description:
      "Multi-tier centrepieces, tasted and finalised well in advance.",
    image: IMG.elegantCake,
    featured: false,
    sortOrder: 4,
    prepTimeHours: 72,
  },
  {
    name: "Designer Cakes",
    slug: "designer-cakes",
    icon: "🎨",
    description: "Fondant sculpting, hand-piped detail and theme builds.",
    image: IMG.cake7,
    featured: false,
    sortOrder: 5,
    prepTimeHours: 36,
  },
  {
    name: "Photo Cakes",
    slug: "photo-cakes",
    icon: "🖼️",
    description: "Edible-print cakes from the photo you can't stop looking at.",
    image: IMG.cake9,
    featured: false,
    sortOrder: 6,
    prepTimeHours: 24,
  },
  {
    name: "Kids Cakes",
    slug: "kids-cakes",
    icon: "🧸",
    description: "Characters, colours and shapes that make small people gasp.",
    image: IMG.cake13,
    featured: false,
    sortOrder: 7,
    prepTimeHours: 24,
  },
  {
    name: "Cheesecakes",
    slug: "cheesecakes",
    icon: "🍰",
    description: "Baked and set cheesecakes, dense and properly creamy.",
    image: IMG.cheesecake,
    featured: false,
    sortOrder: 8,
    prepTimeHours: 12,
  },
  {
    name: "Brownies",
    slug: "brownies",
    icon: "🍫",
    description: "Fudgy centres, crackled tops, tubs and slabs.",
    image: IMG.brownies,
    featured: false,
    sortOrder: 9,
    prepTimeHours: 6,
  },
  {
    name: "Cookies & Treats",
    slug: "cookies-and-treats",
    icon: "🍪",
    description:
      "Fresh cookies, brownies, desserts and small chocolate indulgences.",
    image: IMG.cookies,
    featured: true,
    sortOrder: 10,
    prepTimeHours: 6,
  },
  {
    name: "Gift Hampers",
    slug: "gift-hampers",
    icon: "🎁",
    description:
      "Curated boxes full of cookies, chocolates and thoughtful details.",
    image: IMG.macarons,
    featured: true,
    sortOrder: 11,
    prepTimeHours: 12,
  },
  {
    name: "Chocolates",
    slug: "chocolates",
    icon: "🍬",
    description: "Hand-flavoured bars, bonbons and festive boxes.",
    image: IMG.chocolate,
    featured: false,
    sortOrder: 12,
    prepTimeHours: 8,
  },
  {
    name: "Fresh Breads",
    slug: "fresh-breads",
    icon: "🥖",
    description: "Sourdough, focaccia and everyday loaves baked each morning.",
    image: IMG.bread,
    featured: false,
    sortOrder: 13,
    prepTimeHours: 12,
  },
  {
    name: "Better Bakes",
    slug: "better-bakes",
    icon: "🌾",
    description: "Gluten-free breads and mindful savoury snackables.",
    image: IMG.jalapenoSnacks,
    featured: true,
    sortOrder: 14,
    prepTimeHours: 12,
  },
];

const cakeFlavours = [
  { name: "Belgian Chocolate", surcharge: 150, premium: true },
  { name: "Dark Chocolate Truffle", surcharge: 120, premium: true },
  { name: "Vanilla Bean", surcharge: 0 },
  { name: "Red Velvet", surcharge: 100 },
  { name: "Butterscotch", surcharge: 60 },
  { name: "Black Forest", surcharge: 80 },
  { name: "Pineapple", surcharge: 0 },
  { name: "Blueberry", surcharge: 130, premium: true },
  { name: "Strawberry", surcharge: 70 },
  { name: "Lotus Biscoff", surcharge: 200, premium: true },
  { name: "Hazelnut Praline", surcharge: 180, premium: true },
];

const cakeFillings = [
  { name: "Chocolate Ganache", surcharge: 100 },
  { name: "Cream Cheese", surcharge: 120 },
  { name: "Fresh Fruit", surcharge: 90 },
  { name: "Hazelnut Crunch", surcharge: 140 },
  { name: "Vanilla Cream", surcharge: 0 },
  { name: "Salted Caramel", surcharge: 130 },
];

const cakeShapes = [
  { name: "Round", surcharge: 0 },
  { name: "Square", surcharge: 50 },
  { name: "Heart", surcharge: 150 },
  { name: "Rectangle", surcharge: 80 },
  { name: "Tall / Barrel", surcharge: 300 },
];

const standardWeights = (base: number) => [
  { label: "500 g", grams: 500, price: base, servings: "4–6 servings" },
  {
    label: "1 kg",
    grams: 1000,
    price: Math.round(base * 1.72),
    servings: "8–12 servings",
  },
  {
    label: "1.5 kg",
    grams: 1500,
    price: Math.round(base * 2.48),
    servings: "12–18 servings",
  },
  {
    label: "2 kg",
    grams: 2000,
    price: Math.round(base * 3.18),
    servings: "18–24 servings",
  },
  {
    label: "3 kg",
    grams: 3000,
    price: Math.round(base * 4.62),
    servings: "26–34 servings",
  },
];

const pastryWeights = (single: number) => [
  { label: "Single pastry", grams: 120, price: single },
  { label: "Box of 4", grams: 480, price: Math.round(single * 3.8) },
  { label: "Box of 8", grams: 960, price: Math.round(single * 7.2) },
];

const sliceWeights = (single: number) => [
  { label: "Single slice", grams: 140, price: single },
  { label: "Box of 4", grams: 560, price: Math.round(single * 3.8) },
];

export const products = [
  {
    name: "Belgian Chocolate Truffle Cake",
    slug: "belgian-chocolate-truffle-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Three layers of dark chocolate sponge, Belgian ganache and a mirror glaze finish.",
    description:
      "Our most-ordered celebration cake. Moist chocolate sponge is soaked in cocoa syrup, layered with a slow-stirred Belgian ganache, then finished with a glossy mirror glaze and dark chocolate curls. Rich without being heavy — the kind of cake that disappears before the candles cool.",
    images: [IMG.chocolateTruffleCake],
    base: 650,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["chocolate", "bestseller", "birthday", "eggless"],
    occasions: ["Birthday", "Anniversary", "Just because"],
    featured: true,
    bestseller: true,
    prepTimeHours: 8,
    ingredients:
      "Refined flour, Belgian dark chocolate (54%), fresh cream, cocoa powder, castor sugar, butter, milk, vanilla extract.",
    allergens: "Contains milk, wheat and soy. May contain traces of nuts.",
    storageInstructions:
      "Refrigerate at 4°C. Bring to room temperature 20 minutes before serving. Best enjoyed within 48 hours.",
    salesCount: 412,
  },
  {
    name: "Classic Red Velvet Cake",
    slug: "classic-red-velvet-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Deep cocoa-red sponge layered with tangy cream cheese frosting.",
    description:
      "A properly balanced red velvet — cocoa-forward, never just food colouring. Buttermilk sponge is layered with a cream cheese frosting we whip to order so it stays light, then finished with velvet crumb around the sides.",
    images: [IMG.cake6],
    base: 700,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["red velvet", "cream cheese", "birthday"],
    occasions: ["Birthday", "Anniversary", "Valentine's Day"],
    featured: true,
    bestseller: true,
    prepTimeHours: 8,
    ingredients:
      "Refined flour, buttermilk, cocoa powder, cream cheese, butter, castor sugar, vinegar, natural colour.",
    allergens: "Contains milk, wheat and egg (unless ordered eggless).",
    storageInstructions: "Refrigerate. Consume within 48 hours.",
    salesCount: 318,
  },
  {
    name: "Fresh Blueberry Cream Cake",
    slug: "fresh-blueberry-cream-cake",
    categorySlug: "anniversary-cakes",
    shortDescription:
      "Vanilla sponge, blueberry compote and lightly sweetened whipped cream.",
    description:
      "Made for people who find most cakes too sweet. Soft vanilla sponge, a compote we cook down from real blueberries, and cream whipped to soft peaks. Finished with fresh berries and a dusting of icing sugar.",
    images: [IMG.blueberryCake],
    base: 780,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["blueberry", "fruit", "light", "anniversary"],
    occasions: ["Anniversary", "Birthday", "Engagement"],
    featured: true,
    prepTimeHours: 12,
    ingredients:
      "Refined flour, fresh blueberries, dairy cream, castor sugar, butter, vanilla, lemon zest.",
    allergens: "Contains milk and wheat.",
    storageInstructions:
      "Refrigerate and serve within 24 hours for best texture.",
    salesCount: 176,
  },
  {
    name: "Classic Blackforest Cake",
    slug: "classic-blackforest-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Whipped cream, chocolate shavings and cherry-topped chocolate sponge.",
    description:
      "A familiar celebration classic with soft chocolate sponge, whipped cream, cherry notes and a generous shower of chocolate shavings. Finished with cherries and a dark chocolate drip.",
    images: [IMG.blackforestCake],
    base: 620,
    flavours: cakeFlavours,
    fillings: cakeFillings.slice(0, 4),
    shapes: cakeShapes,
    tags: ["blackforest", "chocolate", "birthday", "classic"],
    occasions: ["Birthday", "Anniversary", "Office party"],
    featured: true,
    bestseller: true,
    prepTimeHours: 8,
    ingredients:
      "Chocolate sponge, dairy cream, chocolate shavings, cherries, milk, cocoa and vanilla.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions:
      "Refrigerate at 4°C and consume within 24–36 hours for best texture.",
    salesCount: 288,
  },
  {
    name: "Butterscotch Cake",
    slug: "butterscotch-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Soft vanilla sponge with butterscotch cream and crunchy praline pearls.",
    description:
      "A mellow, creamy butterscotch cake finished with piped vanilla cream, caramel notes and a crisp praline bite in every slice.",
    images: [IMG.butterscotchCake],
    base: 640,
    flavours: cakeFlavours,
    fillings: cakeFillings.slice(0, 5),
    shapes: cakeShapes,
    tags: ["butterscotch", "birthday", "classic", "eggless"],
    occasions: ["Birthday", "Anniversary", "Family dinner"],
    featured: true,
    prepTimeHours: 8,
    ingredients:
      "Vanilla sponge, dairy cream, butterscotch, caramel crunch, milk and butter.",
    allergens: "Contains milk and wheat. May contain nuts.",
    storageInstructions:
      "Refrigerate. Bring to room temperature 15 minutes before serving.",
    salesCount: 230,
  },
  {
    name: "Chocolate Mousse Cake",
    slug: "chocolate-mousse-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Chocolate sponge layered with light mousse and piped chocolate cream.",
    description:
      "A lighter take on a chocolate celebration cake: airy mousse, soft sponge, glossy chocolate accents and a ring of piped chocolate cream.",
    images: [IMG.chocolateMousseCake],
    base: 780,
    flavours: cakeFlavours,
    fillings: cakeFillings.slice(0, 4),
    shapes: cakeShapes,
    tags: ["chocolate mousse", "chocolate", "birthday", "premium"],
    occasions: ["Birthday", "Anniversary", "Just because"],
    featured: true,
    prepTimeHours: 10,
    ingredients:
      "Chocolate sponge, dairy cream, cocoa, couverture chocolate, milk and butter.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Keep refrigerated and serve chilled.",
    salesCount: 196,
  },
  {
    name: "Pineapple Cream Cake",
    slug: "pineapple-cream-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Bright pineapple cream cake with soft sponge and a sunny yellow finish.",
    description:
      "A gentle fruit-forward cake with pineapple compote, whipped cream and soft vanilla sponge. Finished with yellow cream work and pineapple slices.",
    images: [IMG.pineappleCake],
    base: 600,
    flavours: cakeFlavours,
    fillings: cakeFillings.slice(0, 5),
    shapes: cakeShapes,
    tags: ["pineapple", "fruit", "birthday", "eggless"],
    occasions: ["Birthday", "Anniversary", "Family dinner"],
    prepTimeHours: 8,
    ingredients:
      "Vanilla sponge, pineapple, dairy cream, milk, butter and vanilla.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Refrigerate and enjoy within 36 hours.",
    salesCount: 210,
  },
  {
    name: "Pineapple Floral Cake",
    slug: "pineapple-floral-cake",
    categorySlug: "designer-cakes",
    shortDescription:
      "Minimal pineapple-toned cake with floral cream work and a clean gold base.",
    description:
      "A softer designer finish for fruit-cake lovers: pineapple cream, vanilla sponge and floral piping over a smooth pale-yellow finish.",
    images: [IMG.pineappleFloralCake],
    base: 760,
    flavours: cakeFlavours,
    fillings: cakeFillings.slice(0, 5),
    shapes: cakeShapes,
    tags: ["pineapple", "designer", "floral", "celebration"],
    occasions: ["Birthday", "Anniversary", "Engagement"],
    prepTimeHours: 12,
    ingredients:
      "Vanilla sponge, pineapple compote, dairy cream, milk, butter and vanilla.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Refrigerate and enjoy within 36 hours.",
    salesCount: 104,
  },
  {
    name: "Strawberry Cream Cake",
    slug: "strawberry-cream-cake",
    categorySlug: "anniversary-cakes",
    shortDescription:
      "Pink strawberry cream cake finished with soft piping and rose detail.",
    description:
      "A cheerful strawberry cake with soft sponge, strawberry cream and hand-piped pink detail. Made for birthdays, anniversaries and small celebrations.",
    images: [IMG.strawberryCake],
    base: 680,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["strawberry", "fruit", "anniversary", "birthday"],
    occasions: ["Birthday", "Anniversary", "Valentine's Day"],
    featured: true,
    prepTimeHours: 8,
    ingredients:
      "Vanilla sponge, strawberry cream, dairy cream, milk, butter and vanilla.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Refrigerate and consume within 36 hours.",
    salesCount: 242,
  },
  {
    name: "Vanilla Celebration Cake",
    slug: "vanilla-celebration-cake",
    categorySlug: "birthday-cakes",
    shortDescription:
      "Clean vanilla cream cake with a soft green accent and smooth finish.",
    description:
      "A simple, versatile vanilla cake for messages, candles and elegant small gatherings. Light sponge, vanilla cream and a neat piped finish.",
    images: [IMG.vanillaCake],
    base: 580,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["vanilla", "classic", "birthday", "eggless"],
    occasions: ["Birthday", "Anniversary", "Just because"],
    prepTimeHours: 8,
    ingredients:
      "Vanilla sponge, dairy cream, milk, butter, vanilla extract and sugar.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions:
      "Refrigerate. Bring to room temperature before cutting.",
    salesCount: 205,
  },
  {
    name: "Strawberry Blueberry Mix Cake",
    slug: "strawberry-blueberry-mix-cake",
    categorySlug: "anniversary-cakes",
    shortDescription:
      "A square fruit-cream cake with strawberry, blueberry and butterfly detail.",
    description:
      "A neat square cake layered with strawberry and blueberry notes, finished with cream texture, gold accents and soft butterfly detail.",
    images: [IMG.strawberryBlueberryMixCake],
    base: 820,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["strawberry", "blueberry", "fruit", "designer"],
    occasions: ["Birthday", "Anniversary", "Engagement"],
    prepTimeHours: 12,
    ingredients:
      "Vanilla sponge, strawberry compote, blueberry compote, dairy cream, milk and butter.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Refrigerate and serve within 36 hours.",
    salesCount: 132,
  },
  {
    name: "Lotus Biscoff Celebration Cake",
    slug: "lotus-biscoff-celebration-cake",
    categorySlug: "designer-cakes",
    shortDescription:
      "Caramelised biscuit sponge, Biscoff spread and a crunchy speculoos crumb.",
    description:
      "Layers of brown-butter sponge brushed with caramel syrup, filled with whipped Biscoff cream and a speculoos crumb for crunch. Finished with a poured Biscoff glaze and whole biscuits around the crown.",
    images: [IMG.biscoffCheesecakeSlice],
    base: 900,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["biscoff", "caramel", "premium", "designer"],
    occasions: ["Birthday", "Corporate", "Farewell"],
    featured: true,
    bestseller: true,
    prepTimeHours: 24,
    ingredients:
      "Refined flour, Lotus Biscoff spread and biscuits, dairy cream, brown butter, castor sugar.",
    allergens: "Contains milk, wheat and soy.",
    storageInstructions: "Refrigerate. Best within 48 hours.",
    salesCount: 254,
  },
  {
    name: "Two-Tier Wedding Cake",
    slug: "two-tier-wedding-cake",
    categorySlug: "wedding-cakes",
    shortDescription:
      "A tasted-and-approved two-tier centrepiece, finished in buttercream or fondant.",
    description:
      "Our wedding tier starts with a tasting session, then a design conversation about height, texture, florals and colour. Every tier is baked fresh, dowelled properly, and delivered assembled to your venue in Bikaner.",
    images: [IMG.tieredCake],
    base: 2400,
    weights: [
      {
        label: "2 kg (2 tiers)",
        grams: 2000,
        price: 4800,
        servings: "20–26 servings",
      },
      {
        label: "3 kg (2 tiers)",
        grams: 3000,
        price: 6900,
        servings: "30–40 servings",
      },
      {
        label: "5 kg (3 tiers)",
        grams: 5000,
        price: 11500,
        servings: "55–70 servings",
      },
      {
        label: "8 kg (3 tiers)",
        grams: 8000,
        price: 18400,
        servings: "90–110 servings",
      },
    ],
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: [
      { name: "Round", surcharge: 0 },
      { name: "Square", surcharge: 400 },
    ],
    tags: ["wedding", "tiered", "premium"],
    occasions: ["Wedding", "Engagement"],
    featured: false,
    prepTimeHours: 72,
    ingredients: "Discussed and finalised at your tasting session.",
    allergens:
      "Contains milk and wheat. Nut-free options available on request.",
    storageInstructions:
      "Delivered chilled and assembled. Keep away from direct heat until cutting.",
    salesCount: 41,
  },
  {
    name: "Edible Photo Print Cake",
    slug: "edible-photo-print-cake",
    categorySlug: "photo-cakes",
    shortDescription:
      "Your photo, printed on edible sheet over vanilla or chocolate sponge.",
    description:
      "Send the photo at checkout or on WhatsApp and we'll print it on a food-grade edible sheet, set over your chosen sponge with a piped border. Sharpest results come from a well-lit photo with the subject centred.",
    images: [IMG.cake9],
    base: 850,
    flavours: cakeFlavours.slice(0, 6),
    fillings: cakeFillings.slice(0, 4),
    shapes: [
      { name: "Round", surcharge: 0 },
      { name: "Square", surcharge: 0 },
      { name: "Rectangle", surcharge: 100 },
    ],
    tags: ["photo cake", "personalised", "birthday"],
    occasions: ["Birthday", "Anniversary", "Farewell", "Corporate"],
    prepTimeHours: 24,
    ingredients:
      "Sponge base of your choice, edible ink print, whipped frosting.",
    allergens: "Contains milk and wheat.",
    storageInstructions:
      "Refrigerate. Avoid condensation on the print — uncover just before serving.",
    salesCount: 203,
  },
  {
    name: "Jungle Safari Kids Cake",
    slug: "jungle-safari-kids-cake",
    categorySlug: "kids-cakes",
    shortDescription:
      "Hand-modelled animals, buttercream grass and a chocolate-mud base.",
    description:
      "A birthday cake built for a five-year-old audience: chocolate mud sponge, buttercream grass piped in three greens, and hand-modelled fondant animals. Tell us the favourite animal and we'll make it the centrepiece.",
    images: [IMG.cake13],
    base: 1100,
    flavours: cakeFlavours.slice(0, 7),
    fillings: cakeFillings.slice(0, 4),
    shapes: cakeShapes.slice(0, 3),
    tags: ["kids", "theme", "fondant", "designer"],
    occasions: ["Birthday"],
    prepTimeHours: 36,
    ingredients: "Chocolate mud sponge, buttercream, fondant, natural colours.",
    allergens: "Contains milk, wheat and soy.",
    storageInstructions:
      "Keep cool and away from sunlight. Fondant softens in heat.",
    salesCount: 118,
  },
  {
    name: "New York Baked Cheesecake",
    slug: "new-york-baked-cheesecake",
    categorySlug: "cheesecakes",
    shortDescription:
      "Dense, slow-baked cheesecake on a buttery digestive base.",
    description:
      "Baked low and slow in a water bath so the centre stays silky and the top never cracks. Cream cheese, a whisper of lemon, and a digestive base pressed with browned butter. Served plain or with a berry compote.",
    images: [IMG.cheesecakeWhole],
    base: 750,
    weights: [
      { label: "500 g", grams: 500, price: 750, servings: "5–6 servings" },
      { label: "1 kg", grams: 1000, price: 1350, servings: "10–12 servings" },
      { label: "1.5 kg", grams: 1500, price: 1950, servings: "14–18 servings" },
    ],
    flavours: [
      { name: "Classic New York", surcharge: 0 },
      { name: "Blueberry", surcharge: 150 },
      { name: "Biscoff", surcharge: 200, premium: true },
      { name: "Mango", surcharge: 120 },
    ],
    fillings: [],
    shapes: [{ name: "Round", surcharge: 0 }],
    tags: ["cheesecake", "baked", "bestseller"],
    occasions: ["Birthday", "Just because", "Corporate"],
    bestseller: true,
    eggOptions: ["with-egg", "eggless"],
    prepTimeHours: 12,
    ingredients:
      "Cream cheese, digestive biscuits, butter, castor sugar, eggs, lemon, vanilla.",
    allergens: "Contains milk, wheat and egg.",
    storageInstructions: "Refrigerate up to 4 days. Do not freeze once cut.",
    salesCount: 389,
  },
  {
    name: "Biscoff Cheesecake Slice",
    slug: "biscoff-cheesecake-slice",
    categorySlug: "cheesecakes",
    shortDescription:
      "Creamy cheesecake slice finished with Lotus Biscoff spread and biscuit.",
    description:
      "A chilled cheesecake slice with a biscuit base, creamy centre and a generous Biscoff finish. Easy to box for gifting or add beside a celebration order.",
    images: [IMG.biscoffCheesecakeSlice],
    base: 240,
    weights: sliceWeights(240),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["biscoff", "cheesecake", "slice", "premium"],
    occasions: ["Just because", "Gifting", "Corporate"],
    bestseller: true,
    eggOptions: ["with-egg", "eggless"],
    unlimitedStock: false,
    stock: 30,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Cream cheese, dairy cream, Biscoff spread, Lotus biscuit, digestive base and butter.",
    allergens: "Contains milk, wheat and soy.",
    storageInstructions: "Keep refrigerated and consume within 3 days.",
    salesCount: 276,
  },
  {
    name: "Blueberry Cheesecake Slice",
    slug: "blueberry-cheesecake-slice",
    categorySlug: "cheesecakes",
    shortDescription:
      "Classic cheesecake slice topped with glossy blueberry compote.",
    description:
      "A smooth cheesecake slice on a biscuit base, topped with slow-cooked blueberry compote. Tart, creamy and balanced.",
    images: [IMG.blueberryCheesecakeSlice],
    base: 230,
    weights: sliceWeights(230),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["blueberry", "cheesecake", "slice", "fruit"],
    occasions: ["Just because", "Gifting", "Corporate"],
    eggOptions: ["with-egg", "eggless"],
    unlimitedStock: false,
    stock: 30,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Cream cheese, blueberry compote, digestive base, dairy cream and butter.",
    allergens: "Contains milk and wheat.",
    storageInstructions: "Keep refrigerated and consume within 3 days.",
    salesCount: 214,
  },
  {
    name: "Nutella Cheesecake Slice",
    slug: "nutella-cheesecake-slice",
    categorySlug: "cheesecakes",
    shortDescription:
      "Creamy cheesecake slice topped with Nutella and a biscuit base.",
    description:
      "A compact slice for chocolate-hazelnut cravings: creamy cheesecake, a crisp base and a smooth Nutella layer.",
    images: [IMG.nutellaCheesecakeSlice],
    base: 250,
    weights: sliceWeights(250),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["nutella", "cheesecake", "slice", "chocolate"],
    occasions: ["Just because", "Gifting", "Corporate"],
    bestseller: true,
    eggOptions: ["with-egg", "eggless"],
    unlimitedStock: false,
    stock: 30,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Cream cheese, Nutella, digestive base, dairy cream, butter and hazelnut.",
    allergens: "Contains milk, wheat, soy and hazelnut.",
    storageInstructions: "Keep refrigerated and consume within 3 days.",
    salesCount: 251,
  },
  {
    name: "Chocolate Mousse Pastry",
    slug: "chocolate-mousse-pastry",
    categorySlug: "cookies-and-treats",
    shortDescription:
      "Chocolate sponge layered with mousse and finished as a neat single pastry.",
    description:
      "A clean, sliceable chocolate pastry with airy mousse, dark sponge layers and piped chocolate cream on top. Best for single-serve dessert boxes and office treats.",
    images: [IMG.chocolateMoussePastry],
    base: 160,
    weights: pastryWeights(160),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["pastry", "chocolate", "mousse", "single serve"],
    occasions: ["Just because", "Gifting", "Office party"],
    bestseller: true,
    unlimitedStock: false,
    stock: 45,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Chocolate sponge, dairy cream, cocoa, couverture chocolate, milk and butter.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Keep refrigerated and consume within 48 hours.",
    salesCount: 264,
  },
  {
    name: "Pineapple Pastry",
    slug: "pineapple-pastry",
    categorySlug: "cookies-and-treats",
    shortDescription:
      "Light pineapple pastry with soft sponge, cream and fruit filling.",
    description:
      "A chilled pineapple pastry with tender vanilla sponge, whipped cream and bright pineapple notes. Easy to pack for small celebrations.",
    images: [IMG.pineapplePastry],
    base: 130,
    weights: pastryWeights(130),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["pastry", "pineapple", "fruit", "single serve"],
    occasions: ["Just because", "Gifting", "Family dinner"],
    unlimitedStock: false,
    stock: 40,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Vanilla sponge, pineapple, dairy cream, milk, butter and vanilla.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Keep refrigerated and consume within 48 hours.",
    salesCount: 188,
  },
  {
    name: "Strawberry Blueberry Mix Pastry",
    slug: "strawberry-blueberry-mix-pastry",
    categorySlug: "cookies-and-treats",
    shortDescription:
      "Layered pastry with strawberry and blueberry cream through vanilla sponge.",
    description:
      "A pretty single pastry with alternating strawberry and blueberry layers, soft sponge and a light cream finish.",
    images: [IMG.strawberryBlueberryMixPastry],
    base: 150,
    weights: pastryWeights(150),
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["pastry", "strawberry", "blueberry", "fruit"],
    occasions: ["Just because", "Gifting", "Anniversary"],
    unlimitedStock: false,
    stock: 40,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Vanilla sponge, strawberry compote, blueberry compote, dairy cream, milk and butter.",
    allergens: "Contains milk and wheat. Eggless option available.",
    storageInstructions: "Keep refrigerated and consume within 48 hours.",
    salesCount: 172,
  },
  {
    name: "Chocolate Cupcakes",
    slug: "chocolate-cupcakes",
    categorySlug: "cookies-and-treats",
    shortDescription:
      "Chocolate cupcakes with generous dark chocolate rose piping.",
    description:
      "Soft chocolate cupcakes topped with rich dark chocolate frosting, boxed for birthdays, gifting and snack tables.",
    images: [IMG.chocolateCupcakes],
    base: 360,
    weights: [
      { label: "Box of 4", grams: 360, price: 360 },
      { label: "Box of 6", grams: 540, price: 520 },
      { label: "Box of 12", grams: 1080, price: 980 },
    ],
    flavours: [
      { name: "Dark Chocolate", surcharge: 0 },
      { name: "Chocolate Hazelnut", surcharge: 80, premium: true },
      { name: "Mocha", surcharge: 50 },
    ],
    fillings: [],
    shapes: [],
    tags: ["cupcakes", "chocolate", "gifting", "birthday"],
    occasions: ["Birthday", "Gifting", "Corporate"],
    featured: true,
    unlimitedStock: false,
    stock: 48,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Refined flour, cocoa, dark chocolate, dairy cream, butter, sugar and vanilla.",
    allergens: "Contains milk, wheat and soy. Eggless option available.",
    storageInstructions: "Keep refrigerated and consume within 48 hours.",
    salesCount: 276,
  },
  {
    name: "Nutella Brownie Tub",
    slug: "nutella-brownie-tub",
    categorySlug: "brownies",
    shortDescription:
      "Warm fudge brownie layered with Nutella in a spoonable tub.",
    description:
      "Our fudgiest brownie broken into a tub and layered with Nutella and a little sea salt. Meant to be eaten with a spoon, straight from the fridge, with no plate involved.",
    images: [IMG.brownie],
    base: 260,
    weights: [
      {
        label: "Single tub (250 g)",
        grams: 250,
        price: 260,
        servings: "1–2 servings",
      },
      {
        label: "Twin pack (500 g)",
        grams: 500,
        price: 480,
        servings: "3–4 servings",
      },
      {
        label: "Party pack (1 kg)",
        grams: 1000,
        price: 900,
        servings: "8–10 servings",
      },
    ],
    flavours: [
      { name: "Nutella", surcharge: 0 },
      { name: "Salted Caramel", surcharge: 40 },
      { name: "Biscoff", surcharge: 60 },
      { name: "Walnut", surcharge: 50 },
    ],
    fillings: [],
    shapes: [],
    tags: ["brownie", "nutella", "dessert", "bestseller"],
    occasions: ["Just because", "Gifting"],
    bestseller: true,
    featured: true,
    unlimitedStock: false,
    stock: 40,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Dark chocolate, butter, refined flour, eggs, castor sugar, Nutella, sea salt.",
    allergens: "Contains milk, wheat, egg, soy and hazelnuts.",
    storageInstructions: "Refrigerate and eat within 4 days.",
    salesCount: 640,
  },
  {
    name: "Classic Chocolate Chip Cookies",
    slug: "classic-chocolate-chip-cookies",
    categorySlug: "cookies-and-treats",
    shortDescription:
      "Brown-butter cookies with pools of dark chocolate and flaky salt.",
    description:
      "Dough rested 24 hours for depth, baked until the edges set and the centres stay soft. Studded with couverture chocolate and finished with flaky salt.",
    images: [IMG.cookies2],
    base: 320,
    weights: [
      { label: "Box of 6", grams: 300, price: 320 },
      { label: "Box of 12", grams: 600, price: 590 },
      { label: "Box of 24", grams: 1200, price: 1120 },
    ],
    flavours: [
      { name: "Dark Chocolate Chip", surcharge: 0 },
      { name: "Double Chocolate", surcharge: 40 },
      { name: "Oatmeal Raisin", surcharge: 0 },
      { name: "Red Velvet", surcharge: 50 },
    ],
    fillings: [],
    shapes: [],
    tags: ["cookies", "gifting", "everyday"],
    occasions: ["Gifting", "Corporate", "Just because"],
    unlimitedStock: false,
    stock: 60,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Refined flour, brown butter, couverture chocolate, brown sugar, eggs, vanilla, sea salt.",
    allergens: "Contains milk, wheat, egg and soy.",
    storageInstructions: "Airtight at room temperature for up to 7 days.",
    salesCount: 502,
  },
  {
    name: "The Celebration Hamper",
    slug: "the-celebration-hamper",
    categorySlug: "gift-hampers",
    shortDescription:
      "Cookies, brownies, chocolates and a handwritten note in a keepsake box.",
    description:
      "Our most-gifted box: a dozen cookies, four brownie squares, a bar of hand-flavoured chocolate, and a handwritten card in your words. Wrapped in cloth and ribbon, ready to hand over.",
    images: [IMG.assortedChocolate12Pc],
    base: 1450,
    weights: [
      { label: "Petite", grams: 700, price: 1450 },
      { label: "Signature", grams: 1400, price: 2450 },
      { label: "Grand", grams: 2500, price: 3950 },
    ],
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["hamper", "gifting", "festive", "corporate"],
    occasions: ["Gifting", "Diwali", "Corporate", "Raksha Bandhan"],
    featured: true,
    unlimitedStock: false,
    stock: 25,
    customisable: false,
    prepTimeHours: 12,
    ingredients: "Assorted bakes — full list enclosed in the box.",
    allergens: "Contains milk, wheat, egg, soy and nuts.",
    storageInstructions:
      "Cool, dry place. Individual items carry their own dates.",
    salesCount: 191,
  },
  {
    name: "Hand-Flavoured Chocolate Box",
    slug: "hand-flavoured-chocolate-box",
    categorySlug: "chocolates",
    shortDescription:
      "Nine bonbons in rotating seasonal flavours, tempered by hand.",
    description:
      "Each box carries nine bonbons across three flavours that rotate with the season — think roasted almond, saffron pista, and dark orange. Tempered by hand for a proper snap.",
    images: [IMG.assortedChocolate12Pc],
    base: 680,
    weights: [
      { label: "Box of 4", grams: 80, price: 360 },
      { label: "Box of 6", grams: 120, price: 520 },
      { label: "Box of 12", grams: 240, price: 980 },
    ],
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["chocolate", "gifting", "festive"],
    occasions: ["Gifting", "Diwali", "Valentine's Day"],
    unlimitedStock: false,
    stock: 35,
    customisable: false,
    prepTimeHours: 8,
    ingredients: "Couverture chocolate, cream, butter, seasonal inclusions.",
    allergens: "Contains milk, soy and nuts.",
    storageInstructions: "Store below 20°C, away from direct sunlight.",
    salesCount: 143,
  },
  {
    name: "Assorted Flavoured Chocolates - 4 Pc",
    slug: "assorted-flavoured-chocolates-4-pc",
    categorySlug: "chocolates",
    shortDescription:
      "A petite four-piece box of handmade flavoured chocolates.",
    description:
      "Four handmade flavoured chocolates packed neatly for small thank-you gifts, table favours and little sweet cravings.",
    images: [IMG.assortedChocolate4Pc],
    base: 360,
    weights: [{ label: "Box of 4", grams: 80, price: 360 }],
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["chocolate", "gifting", "petite box"],
    occasions: ["Gifting", "Corporate", "Just because"],
    unlimitedStock: false,
    stock: 40,
    customisable: false,
    prepTimeHours: 8,
    ingredients: "Couverture chocolate, cream, butter, seasonal inclusions.",
    allergens: "Contains milk, soy and nuts.",
    storageInstructions: "Store below 20°C, away from direct sunlight.",
    salesCount: 94,
  },
  {
    name: "Assorted Flavoured Chocolates - 6 Pc",
    slug: "assorted-flavoured-chocolates-6-pc",
    categorySlug: "chocolates",
    shortDescription:
      "Six colourful handmade chocolates in rotating house flavours.",
    description:
      "A six-piece box of handmade flavoured chocolates, made for compact gifting and festive add-ons.",
    images: [IMG.assortedChocolate6Pc],
    base: 520,
    weights: [{ label: "Box of 6", grams: 120, price: 520 }],
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["chocolate", "gifting", "festive"],
    occasions: ["Gifting", "Diwali", "Corporate"],
    featured: true,
    unlimitedStock: false,
    stock: 35,
    customisable: false,
    prepTimeHours: 8,
    ingredients: "Couverture chocolate, cream, butter, seasonal inclusions.",
    allergens: "Contains milk, soy and nuts.",
    storageInstructions: "Store below 20°C, away from direct sunlight.",
    salesCount: 126,
  },
  {
    name: "Homemade Flavoured Chocolate Bar",
    slug: "homemade-flavoured-chocolate-bar",
    categorySlug: "chocolates",
    shortDescription:
      "A handmade chocolate bar packed for festive gifting and personal notes.",
    description:
      "A moulded flavoured chocolate bar with Bake Baba'z festive packaging, ribbon wrap and a crisp handmade finish.",
    images: [IMG.homemadeFlavorChocolateBar],
    base: 420,
    weights: [
      { label: "Single bar", grams: 110, price: 420 },
      { label: "Pair", grams: 220, price: 800 },
    ],
    flavours: [
      { name: "Strawberry", surcharge: 0 },
      { name: "Dark Chocolate", surcharge: 40 },
      { name: "Pista", surcharge: 60, premium: true },
    ],
    fillings: [],
    shapes: [],
    tags: ["chocolate bar", "gifting", "festive"],
    occasions: ["Gifting", "Diwali", "Raksha Bandhan"],
    unlimitedStock: false,
    stock: 30,
    customisable: false,
    prepTimeHours: 8,
    ingredients:
      "Couverture chocolate, cocoa butter, milk solids and flavouring.",
    allergens: "Contains milk and soy. May contain nuts.",
    storageInstructions: "Store below 20°C, away from direct sunlight.",
    salesCount: 108,
  },
  {
    name: "Country Sourdough Loaf",
    slug: "country-sourdough-loaf",
    categorySlug: "fresh-breads",
    shortDescription:
      "A 36-hour naturally leavened loaf with a blistered, dark crust.",
    description:
      "Wild-yeast starter, a long cold ferment, and a hot bake in a covered pot. Open crumb, sour finish, and a crust that shatters. Baked fresh each morning in limited numbers.",
    images: [IMG.bread],
    base: 220,
    weights: [
      { label: "Half loaf (400 g)", grams: 400, price: 220 },
      { label: "Full loaf (800 g)", grams: 800, price: 380 },
    ],
    flavours: [
      { name: "Classic", surcharge: 0 },
      { name: "Seeded", surcharge: 40 },
      { name: "Olive & Rosemary", surcharge: 60 },
    ],
    fillings: [],
    shapes: [],
    tags: ["bread", "sourdough", "everyday"],
    occasions: ["Everyday"],
    unlimitedStock: false,
    stock: 18,
    customisable: false,
    prepTimeHours: 12,
    ingredients: "Wheat flour, water, natural starter, salt.",
    allergens: "Contains wheat. Made in a kitchen that handles milk and nuts.",
    storageInstructions:
      "Cut side down on a board for 3 days, or freeze sliced.",
    salesCount: 224,
  },
  {
    name: "Gluten-Free Multiseed Loaf",
    slug: "gluten-free-multiseed-loaf",
    categorySlug: "better-bakes",
    shortDescription:
      "A dense, seed-packed loaf made without wheat, and without apology.",
    description:
      "Built on a base of buckwheat and psyllium with sunflower, pumpkin and flax seeds. Holds together for sandwiches, toasts beautifully, and won't crumble the moment you butter it.",
    images: [IMG.bread],
    base: 340,
    weights: [{ label: "Loaf (600 g)", grams: 600, price: 340 }],
    flavours: [],
    fillings: [],
    shapes: [],
    tags: ["gluten-free", "healthy", "bread", "better bakes"],
    occasions: ["Everyday"],
    featured: true,
    unlimitedStock: false,
    stock: 12,
    customisable: false,
    prepTimeHours: 12,
    ingredients:
      "Buckwheat flour, psyllium husk, sunflower seeds, pumpkin seeds, flaxseed, olive oil, salt.",
    allergens: "Gluten-free recipe. Prepared in a kitchen that handles wheat.",
    storageInstructions: "Refrigerate up to 5 days, or freeze sliced.",
    salesCount: 96,
  },
  {
    name: "Just Jalapenos Snack Tub",
    slug: "just-jalapenos-snack-tub",
    categorySlug: "better-bakes",
    shortDescription:
      "Crunchy jalapeno snack mix packed in a ready-to-gift tub.",
    description:
      "A savoury snack tub with jalapeno seasoning and crisp bite-sized pieces. Made for tea-time trays, office desks and gifting baskets.",
    images: [IMG.jalapenoSnacks],
    base: 180,
    weights: [
      { label: "Regular tub", grams: 150, price: 180 },
      { label: "Pack of 2", grams: 300, price: 340 },
    ],
    flavours: [{ name: "Just Jalapenos", surcharge: 0 }],
    fillings: [],
    shapes: [],
    tags: ["snack", "jalapeno", "savoury", "better bakes"],
    occasions: ["Everyday", "Gifting", "Corporate"],
    featured: true,
    unlimitedStock: false,
    stock: 45,
    customisable: false,
    prepTimeHours: 6,
    ingredients:
      "Jalapeno seasoning, grain flour blend, spices, edible oil and salt.",
    allergens: "Prepared in a kitchen that handles wheat, milk, soy and nuts.",
    storageInstructions: "Keep sealed in a cool, dry place.",
    salesCount: 164,
  },
  {
    name: "Signature Custom Cake",
    slug: "signature-custom-cake",
    categorySlug: "custom-cakes",
    shortDescription:
      "Start from a blank canvas — flavour, design, colours and message, all yours.",
    description:
      "The starting point for anything we haven't already baked. Choose the flavour, filling, shape and finish, add your reference images, and we'll build it around your celebration. For the full builder with live pricing, head to Design your own cake.",
    images: [IMG.decorating],
    base: 900,
    flavours: cakeFlavours,
    fillings: cakeFillings,
    shapes: cakeShapes,
    tags: ["custom", "designer", "personalised"],
    occasions: [
      "Birthday",
      "Anniversary",
      "Wedding",
      "Baby shower",
      "Corporate",
    ],
    featured: true,
    prepTimeHours: 24,
    ingredients: "Depends on your chosen flavour and filling.",
    allergens: "Tell us about any allergies and we'll work around them.",
    storageInstructions: "Refrigerate. Serve at room temperature.",
    salesCount: 132,
  },
].map((product) => ({
  ...product,
  weights: product.weights ?? standardWeights(product.base),
}));

export const customizationOptions = [
  // Flavours — the builder's headline choice.
  {
    type: "flavour",
    label: "Chocolate",
    value: "chocolate",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 1,
  },
  {
    type: "flavour",
    label: "Belgian Chocolate",
    value: "belgian-chocolate",
    modifierKind: "per_kg",
    modifierAmount: 150,
    badge: "Premium",
    sortOrder: 2,
  },
  {
    type: "flavour",
    label: "Vanilla",
    value: "vanilla",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 3,
  },
  {
    type: "flavour",
    label: "Red Velvet",
    value: "red-velvet",
    modifierKind: "per_kg",
    modifierAmount: 100,
    sortOrder: 4,
  },
  {
    type: "flavour",
    label: "Butterscotch",
    value: "butterscotch",
    modifierKind: "per_kg",
    modifierAmount: 60,
    sortOrder: 5,
  },
  {
    type: "flavour",
    label: "Black Forest",
    value: "black-forest",
    modifierKind: "per_kg",
    modifierAmount: 80,
    sortOrder: 6,
  },
  {
    type: "flavour",
    label: "Pineapple",
    value: "pineapple",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 7,
  },
  {
    type: "flavour",
    label: "Blueberry",
    value: "blueberry",
    modifierKind: "per_kg",
    modifierAmount: 130,
    badge: "Premium",
    sortOrder: 8,
  },
  {
    type: "flavour",
    label: "Strawberry",
    value: "strawberry",
    modifierKind: "per_kg",
    modifierAmount: 70,
    sortOrder: 9,
  },
  {
    type: "flavour",
    label: "Lotus Biscoff",
    value: "lotus-biscoff",
    modifierKind: "per_kg",
    modifierAmount: 200,
    badge: "Premium",
    sortOrder: 10,
  },
  {
    type: "flavour",
    label: "Hazelnut Praline",
    value: "hazelnut",
    modifierKind: "per_kg",
    modifierAmount: 180,
    badge: "Premium",
    sortOrder: 11,
  },
  {
    type: "flavour",
    label: "Need a recommendation",
    value: "custom",
    modifierKind: "flat",
    modifierAmount: 0,
    description: "We'll suggest something to suit the occasion.",
    sortOrder: 12,
  },

  // Fillings
  {
    type: "filling",
    label: "Chocolate Ganache",
    value: "chocolate-ganache",
    modifierKind: "flat",
    modifierAmount: 100,
    sortOrder: 1,
  },
  {
    type: "filling",
    label: "Cream Cheese",
    value: "cream-cheese",
    modifierKind: "flat",
    modifierAmount: 120,
    sortOrder: 2,
  },
  {
    type: "filling",
    label: "Fresh Fruit",
    value: "fruit",
    modifierKind: "flat",
    modifierAmount: 90,
    sortOrder: 3,
  },
  {
    type: "filling",
    label: "Hazelnut Crunch",
    value: "hazelnut-crunch",
    modifierKind: "flat",
    modifierAmount: 140,
    sortOrder: 4,
  },
  {
    type: "filling",
    label: "Vanilla Cream",
    value: "vanilla-cream",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 5,
  },
  {
    type: "filling",
    label: "Salted Caramel",
    value: "salted-caramel",
    modifierKind: "flat",
    modifierAmount: 130,
    sortOrder: 6,
  },

  // Shapes
  {
    type: "shape",
    label: "Round",
    value: "round",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 1,
  },
  {
    type: "shape",
    label: "Square",
    value: "square",
    modifierKind: "flat",
    modifierAmount: 50,
    sortOrder: 2,
  },
  {
    type: "shape",
    label: "Heart",
    value: "heart",
    modifierKind: "flat",
    modifierAmount: 150,
    sortOrder: 3,
  },
  {
    type: "shape",
    label: "Rectangle",
    value: "rectangle",
    modifierKind: "flat",
    modifierAmount: 80,
    sortOrder: 4,
  },
  {
    type: "shape",
    label: "Tall / Barrel",
    value: "tall",
    modifierKind: "flat",
    modifierAmount: 300,
    extraPrepHours: 12,
    sortOrder: 5,
  },
  {
    type: "shape",
    label: "Number / Letter",
    value: "number",
    modifierKind: "flat",
    modifierAmount: 350,
    extraPrepHours: 12,
    sortOrder: 6,
  },
  {
    type: "shape",
    label: "Custom shape",
    value: "custom",
    modifierKind: "flat",
    modifierAmount: 500,
    extraPrepHours: 24,
    description: "Sculpted to your reference.",
    sortOrder: 7,
  },

  // Styles — these carry most of the design cost and lead time.
  {
    type: "style",
    label: "Minimal",
    value: "minimal",
    modifierKind: "flat",
    modifierAmount: 0,
    description: "Clean finish, restrained detail.",
    sortOrder: 1,
  },
  {
    type: "style",
    label: "Buttercream",
    value: "buttercream",
    modifierKind: "flat",
    modifierAmount: 150,
    description: "Piped textures and soft palette knife work.",
    sortOrder: 2,
  },
  {
    type: "style",
    label: "Floral",
    value: "floral",
    modifierKind: "flat",
    modifierAmount: 350,
    extraPrepHours: 12,
    description: "Piped or fresh florals.",
    sortOrder: 3,
  },
  {
    type: "style",
    label: "Designer",
    value: "designer",
    modifierKind: "flat",
    modifierAmount: 500,
    extraPrepHours: 24,
    description: "Sculpted detail and structured finishes.",
    sortOrder: 4,
  },
  {
    type: "style",
    label: "Fondant",
    value: "fondant",
    modifierKind: "flat",
    modifierAmount: 400,
    extraPrepHours: 24,
    description: "Smooth fondant covering with modelled detail.",
    sortOrder: 5,
  },
  {
    type: "style",
    label: "Photo Cake",
    value: "photo",
    modifierKind: "flat",
    modifierAmount: 150,
    extraPrepHours: 12,
    description: "Edible print from your image.",
    sortOrder: 6,
  },
  {
    type: "style",
    label: "Theme Cake",
    value: "theme",
    modifierKind: "flat",
    modifierAmount: 600,
    extraPrepHours: 24,
    sortOrder: 7,
  },
  {
    type: "style",
    label: "Kids Cake",
    value: "kids",
    modifierKind: "flat",
    modifierAmount: 450,
    extraPrepHours: 24,
    sortOrder: 8,
  },
  {
    type: "style",
    label: "Wedding Cake",
    value: "wedding",
    modifierKind: "flat",
    modifierAmount: 1200,
    extraPrepHours: 48,
    sortOrder: 9,
  },
  {
    type: "style",
    label: "Other / need guidance",
    value: "other",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 10,
  },

  // Tiers
  {
    type: "tier",
    label: "Two tiers",
    value: "2",
    modifierKind: "flat",
    modifierAmount: 750,
    extraPrepHours: 24,
    sortOrder: 2,
  },
  {
    type: "tier",
    label: "Three tiers",
    value: "3",
    modifierKind: "flat",
    modifierAmount: 1800,
    extraPrepHours: 48,
    sortOrder: 3,
  },
  {
    type: "tier",
    label: "Four or more tiers",
    value: "4",
    modifierKind: "flat",
    modifierAmount: 3200,
    extraPrepHours: 72,
    sortOrder: 4,
  },

  // Weights
  {
    type: "weight",
    label: "500 g",
    value: "0.5",
    numericValue: 0.5,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 1,
  },
  {
    type: "weight",
    label: "1 kg",
    value: "1",
    numericValue: 1,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 2,
  },
  {
    type: "weight",
    label: "1.5 kg",
    value: "1.5",
    numericValue: 1.5,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 3,
  },
  {
    type: "weight",
    label: "2 kg",
    value: "2",
    numericValue: 2,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 4,
  },
  {
    type: "weight",
    label: "2.5 kg",
    value: "2.5",
    numericValue: 2.5,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 5,
  },
  {
    type: "weight",
    label: "3 kg",
    value: "3",
    numericValue: 3,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 6,
  },
  {
    type: "weight",
    label: "5 kg",
    value: "5",
    numericValue: 5,
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 7,
  },

  // Occasions
  {
    type: "occasion",
    label: "Birthday",
    value: "birthday",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 1,
  },
  {
    type: "occasion",
    label: "Anniversary",
    value: "anniversary",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 2,
  },
  {
    type: "occasion",
    label: "Wedding",
    value: "wedding",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 3,
  },
  {
    type: "occasion",
    label: "Engagement",
    value: "engagement",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 4,
  },
  {
    type: "occasion",
    label: "Baby Shower",
    value: "baby-shower",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 5,
  },
  {
    type: "occasion",
    label: "Corporate",
    value: "corporate",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 6,
  },
  {
    type: "occasion",
    label: "Farewell",
    value: "farewell",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 7,
  },
  {
    type: "occasion",
    label: "Other",
    value: "other",
    modifierKind: "flat",
    modifierAmount: 0,
    sortOrder: 8,
  },
] as const;

export const addOns = [
  {
    name: "Birthday candles",
    description: "A set of ten tall candles with holders.",
    price: 60,
    group: "Finishing touches",
    sortOrder: 1,
  },
  {
    name: "Number candle",
    description: "One numeral candle in gold or silver.",
    price: 90,
    group: "Finishing touches",
    sortOrder: 2,
  },
  {
    name: "Birthday cake topper",
    description: "Acrylic topper with your text.",
    price: 180,
    group: "Toppers",
    sortOrder: 3,
  },
  {
    name: "Anniversary topper",
    description: "Elegant acrylic 'Happy Anniversary' topper.",
    price: 180,
    group: "Toppers",
    sortOrder: 4,
  },
  {
    name: "Cake knife & server",
    description: "Ribbon-tied knife for the cutting moment.",
    price: 120,
    group: "Finishing touches",
    sortOrder: 5,
  },
  {
    name: "Handwritten greeting card",
    description: "Your message, written by hand.",
    price: 80,
    group: "Gifting",
    sortOrder: 6,
  },
  {
    name: "Fresh flower arrangement",
    description: "Seasonal blooms arranged on or beside the cake.",
    price: 450,
    group: "Gifting",
    sortOrder: 7,
  },
  {
    name: "Edible flowers",
    description: "Food-safe petals set across the finish.",
    price: 250,
    group: "Design",
    sortOrder: 8,
  },
  {
    name: "Chocolate box (9 pc)",
    description: "Add our hand-flavoured bonbons.",
    price: 680,
    group: "Gifting",
    sortOrder: 9,
  },
  {
    name: "Gold leaf detailing",
    description: "Edible 24k gold leaf accents.",
    price: 350,
    group: "Design",
    sortOrder: 10,
  },
  {
    name: "Keepsake gift wrap",
    description: "Cloth wrap and ribbon, ready to hand over.",
    price: 150,
    group: "Gifting",
    sortOrder: 11,
  },
];

export const pricingRules = [
  {
    code: "tier_surcharge",
    label: "Additional tier",
    kind: "flat",
    amount: 750,
    description:
      "Fallback per-tier charge when a tier option isn't configured.",
    sortOrder: 1,
  },
  {
    code: "eggless",
    label: "Eggless recipe",
    kind: "flat",
    amount: 0,
    description: "Set above zero to charge for eggless conversions.",
    sortOrder: 2,
  },
  {
    code: "cake_message",
    label: "Message on cake",
    kind: "flat",
    amount: 0,
    description: "Piped message. Free by default.",
    sortOrder: 3,
  },
  {
    code: "rush_order",
    label: "Priority / rush order",
    kind: "percent",
    amount: 12,
    description: "Applied when the required date falls inside the rush window.",
    sortOrder: 4,
  },
];

export const deliverySlots = [
  {
    label: "10:00 AM – 12:00 PM",
    startTime: "10:00",
    endTime: "12:00",
    sortOrder: 1,
  },
  {
    label: "12:00 PM – 2:00 PM",
    startTime: "12:00",
    endTime: "14:00",
    sortOrder: 2,
  },
  {
    label: "2:00 PM – 4:00 PM",
    startTime: "14:00",
    endTime: "16:00",
    sortOrder: 3,
  },
  {
    label: "4:00 PM – 6:00 PM",
    startTime: "16:00",
    endTime: "18:00",
    sortOrder: 4,
  },
  {
    label: "6:00 PM – 8:00 PM",
    startTime: "18:00",
    endTime: "20:00",
    sortOrder: 5,
  },
  {
    label: "Midnight surprise (11:30 PM – 12:30 AM)",
    startTime: "23:30",
    endTime: "00:30",
    surcharge: 250,
    sortOrder: 6,
  },
];

export const deliveryZones = [
  { pincode: "334001", area: "Bikaner City / Kote Gate", fee: 50 },
  { pincode: "334002", area: "Gangashahar", fee: 70 },
  { pincode: "334003", area: "Bikaner Cantonment", fee: 70 },
  { pincode: "334004", area: "Sri Ramsar", fee: 90 },
  { pincode: "334006", area: "Jaljog / Rani Bazar", fee: 60 },
  {
    pincode: "334401",
    area: "Nokha Road",
    fee: 140,
    minOrder: 800,
    sameDayAvailable: false,
  },
];

export const coupons = [
  {
    code: "WELCOME10",
    description: "10% off your first order",
    type: "percentage",
    value: 10,
    minOrder: 700,
    maxDiscount: 250,
    perUserLimit: 1,
  },
  {
    code: "FREESHIP",
    description: "Free delivery across Bikaner",
    type: "free_delivery",
    value: 0,
    minOrder: 999,
  },
  {
    code: "CELEBRATE500",
    description: "₹500 off large celebration orders",
    type: "fixed",
    value: 500,
    minOrder: 3500,
  },
];

export const faqs = [
  {
    question: "How early should I order a custom cake?",
    answer:
      "Most designs need 24–48 hours. Fondant, sculpted and multi-tier cakes need 48–72 hours, and wedding cakes are best confirmed a week ahead. The builder blocks any date that doesn't leave enough time for the design you've chosen.",
  },
  {
    question: "Can every cake be made eggless?",
    answer:
      "Almost all of them. Every cake on the site offers an eggless option unless the product page says otherwise — a handful of baked cheesecakes rely on egg for structure, and those are marked clearly.",
  },
  {
    question: "Can I upload a cake reference?",
    answer:
      "Yes. The cake builder accepts up to five JPG, PNG or WebP images at 5 MB each. Reference images reach our kitchen with your order, and are the fastest way to get the result you're picturing.",
  },
  {
    question: "Can you copy a reference cake exactly?",
    answer:
      "We treat references as direction rather than a blueprint. We'll match the feel, palette and structure closely, and tell you upfront if something isn't achievable in the size or timeline you've chosen.",
  },
  {
    question: "Can I change an order after payment?",
    answer:
      "Message us on WhatsApp with your order number as soon as you can. Changes are usually possible until we begin baking; after that we can often still adjust the message, toppers and delivery slot.",
  },
  {
    question: "Do you deliver outside Bikaner?",
    answer:
      "We deliver across Bikaner city and nearby PIN codes, each with its own delivery charge shown at checkout. For anywhere further, message us — some orders can be arranged with a courier partner.",
  },
  {
    question: "When is my custom cake confirmed?",
    answer:
      "The moment your payment succeeds. You'll get an order number immediately, and our team will keep you updated as your cake moves through baking, decorating and delivery.",
  },
  {
    question: "What happens if my selected design requires a higher price?",
    answer:
      "The builder prices your design live as you configure it, and the total is recalculated on our servers before payment — so what you see at checkout is what you pay. If a design needs a change after we review it, we'll call you before doing anything.",
  },
];
